### PR TITLE
Add ``--config`` option which accepts a YAML file

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Added the option ``--config`` which accepts a path to a yaml file with the configuration to run `conda-press`.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
It closes #36

**Comment by scopatz** [comment]
Thanks, Marcelo! the code looks good but it looks like there is a test failure on CI

**Comment by marcelotrevisani** [comment]
> Thanks, Marcelo! the code looks good but it looks like there is a test failure on CI

Oh sorry, my mistake! I already fixed, let see if everything will be green again :smile:

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
