### PR TITLE
Bug fix when execute some options with empty values

### PR DESCRIPTION
**Pull request by marcelotrevisani**

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks! it looks like CI is failing.

**Comment by marcelotrevisani** [comment]
> Thanks! it looks like CI is failing.

Yes, sorry! I did a mistake, I am going to fix it tomorrow. I was a bit busy these days

**Comment by scopatz** [comment]
Ok! Thanks!

**Comment by marcelotrevisani** [comment]
I added the ``pytest-console-scripts`` as a dependecy for testing just to easily run the project as a script.

**Comment by marcelotrevisani** [comment]
I think that is fine now, could you please take a look @scopatz ?

**Comment by scopatz** [comment]
Sorry @marcelotrevisani! I have been traveling a lot recently!

**Comment by scopatz** [comment]
This looks great! Thanks for being patient!

**Comment by marcelotrevisani** [comment]
> Sorry @marcelotrevisani! I have been traveling a lot recently!

no problem @scopatz ! I know that we might take sometime to review and contribute for a project  :)
Thanks for the review!

**Pull request merged**
